title: K A K O
description: Khakis and Kick-offs, the Aussie fan’s World Cup 2026 travel toolkit
theme: just-the-docs
color_scheme: kako

url: https://khakisandkickoffs.carrd.co

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

just_the_docs:
  nav_exclude: true
  logo:
    link: https://khakisandkickoffs.carrd.co  # <-- overrides site title link
  footer_content: |
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        const siteTitle = document.querySelector('.site-title a');
        if (siteTitle) {
          siteTitle.href = "https://khakisandkickoffs.carrd.co";
        }
      });
    </script>