title: K A K O
description: Khakis and Kick-offs, the Aussie fan’s World Cup 2026 travel toolkit
theme: just-the-docs
color_scheme: outback

url: https://khakisandkickoffs.carrd.co

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

just_the_docs:
  nav_exclude: true